version: '3.8'
services:
    backend:
      build: ./backend
      ports:
        - "5000:5000"
      environment:
        - MONGO_URI=mongodb://mongo:27017/ongdb
      depends_on:
        - mongo
    frontend:
      build: ./frontend
      ports:
        - "4200:4200"
      depends_on:
        - backend
    mongo:
      image: mongo:5.0
      container_name: project-mongo-1
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
volumes:
  mongo-data: